### ISSUE TITLE
TESIV: CSE Crashes when teleport is activated 

### ISSUE THREAD

**Issue by ShimShon48** [shadeMe/Construction-Set-Extender#12]
My Mod is clean and everything appears to be stable but using CSE to verify teleport, like entering from external to internal areas, CSE crashes. I have installed the OBSE DLL for logging but no results. Teleport crashing does not occur every time but periodically, enough to cause loss of data.

**Comment by shadeMe** [comment]
As I [mentioned earlier](https://github.com/shadeMe/Construction-Set-Extender/issues/11#issuecomment-2088266950), please redirect bug reports to the Nexus page and make sure you provide enough details.
