### ISSUE TITLE
Any way to batch generate lip sync files without the cmd popups?

### ISSUE THREAD

**Issue by Auditormadness9** [shadeMe/Construction-Set-Extender#9]
I searched everywhere on how to launch a bat file so that all its cmd prompts also either launch in the background or just not launch at all. VBS wrapping didn't work and neither did any other registry hack or 3rd party program, and I don't feel like using an entire virtual machine to do this. At the end I've been told to contact the devs or make an issue here to ask for help so I did since I assume it works internally.

The cmds just steal focus every second and it's really annoying. Any way to solve this or any workaround?

Thanks a lot in advance!

**Comment by shadeMe** [comment]
Try the development build - https://1drv.ms/f/s!AjyUCteFHEWwgYh0iBfHbBoKtOEXsA

It should suppress the console windows' creation during lip sync generation.
